apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: exposecontroller
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.exposecontroller.Name }}"
  name: exposecontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      component: "{{ .Release.Name }}-{{ .Values.exposecontroller.Component }}"
  template:
    metadata:
      labels:
        app: {{ .Values.exposecontroller.Name }}
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        component: "{{ .Release.Name }}-{{ .Values.exposecontroller.Component }}"
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: "{{ .Values.exposecontroller.Image }}:{{ .Values.exposecontroller.ImageTag }}"
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/restarteveryday
          initialDelaySeconds: 86164
        name: exposecontroller
        volumeMounts:
        - mountPath: /etc/exposecontroller
          name: config-volume
      serviceAccountName: exposecontroller
      volumes:
      - configMap:
          name: exposecontroller
        name: config-volume