apiVersion: v1
kind: List
items:
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: pipelines.jenkins.io
    labels:
      app: {{ template "jenkins.fullname" . }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: "{{ .Release.Name }}"
      heritage: "{{ .Release.Service }}"
  spec:
    group: jenkins.io
    names:
      kind: Pipeline
      listKind: PipelineList
      plural: pipelines
      shortNames:
      - pipeline
      singular: pipeline
    scope: Namespaced
    version: v1
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: runs.jenkins.io
    labels:
      app: {{ template "jenkins.fullname" . }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: "{{ .Release.Name }}"
      heritage: "{{ .Release.Service }}"
  spec:
    group: jenkins.io
    names:
      kind: Run
      listKind: RunList
      plural: runs
      shortNames:
      - run
      singular: run
    scope: Namespaced
    version: v1

