apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Chart.Name }}-{{ .Release.Name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      component: "{{ .Chart.Name }}-{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        component: "{{ .Chart.Name }}-{{ .Release.Name }}"
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: "{{ .Values.pipelinecontroller.Image }}:{{ .Values.pipelinecontroller.ImageTag }}"
        name: {{ .Chart.Name }}
      serviceAccountName: {{ .Chart.Name }}