apiVersion: v1
data:
{{- if .Values.PipelineSecrets.GithubToken }}
  hub: {{ .Values.PipelineSecrets.GithubToken | b64enc | quote }}
{{- else }}
  hub: ""
{{- end }}
kind: Secret
metadata:
  name: jenkins-hub-api-token
type: Opaque