apiVersion: v1
data:
{{- if .Values.PipelineSecrets.GitSSHPub }}
  ssh-key.pub: {{ .Values.PipelineSecrets.GitSSHPub | b64enc | quote }}
{{- else }}
  ssh-key.pub: ""
{{- end }}
{{- if .Values.PipelineSecrets.GitSSH }}
  ssh-key: {{ .Values.PipelineSecrets.GitSSH | b64enc | quote }}
{{- else }}
  ssh-key: ""
{{- end }}
kind: Secret
metadata:
  name: jenkins-git-ssh
type: Opaque