apiVersion: v1
data:
{{- if .Values.PipelineSecrets.GPG }}
  pubring.gpg: {{ .Values.PipelineSecrets.GPG.pubring | b64enc | quote }}
  sec-jenkins.gpg: {{ .Values.PipelineSecrets.GPG.secjenkins | b64enc | quote }}
  secring.gpg: {{ .Values.PipelineSecrets.GPG.secring | b64enc | quote }}
  trustdb.gpg: {{ .Values.PipelineSecrets.GPG.trustdb | b64enc | quote }}
{{- else }}
  pubring.gpg: ""
  sec-jenkins.gpg: ""
  secring.gpg: ""
  trustdb.gpg: ""
{{- end }}
kind: Secret
metadata:
  name: jenkins-release-gpg
type: Opaque