apiVersion: v1
data:
{{- if .Values.PipelineSecrets.NPMToken }}
  token: {{ .Values.PipelineSecrets.NPMToken | b64enc | quote }}
{{- else }}
  token: ""
{{- end }}
kind: Secret
metadata:
  name: npm-token
type: Opaque