apiVersion: v1
data:
{{- if .Values.PipelineSecrets.SSHConfig }}
  .config: {{ .Values.PipelineSecrets.SSHConfig | b64enc | quote }}
{{- else }}
  .config: ""
{{- end }}
kind: Secret
metadata:
  name: jenkins-ssh-config
type: Opaque